import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Layout from "@/layouts/Layout";
import Provider from "@/layouts/Provider";
import { getServerSession } from "next-auth";
import { options } from "@/config/Option";
import { Toaster } from "@/components/ui/sonner";
const inter = Poppins({
  weight: ["600", "900", "800", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(options);
  return (
    <html lang="en">
      <body
        className={`h-screen bg-black flex relative justify-center overflow-hidden
         ${inter.className}`}
      >
        <div className="-z-10 absolute  bg-teal rounded-r-full h-96 left-[30rem] top-52 w-96 blur-3xl opacity-40"></div>
        <div className="-z-10 absolute  bg-red rounded-r-full h-96 right-96 top-20 w-96 blur-3xl opacity-40"></div>
        <div className="-z-10 absolute  bg-yellow rounded-tr-full h-96 right-40 bottom-12 w-[30rem] blur-3xl opacity-40"></div>
        <Provider session={session}>
          <Layout>{children}</Layout>
          <Toaster />
        </Provider>
      </body>
    </html>
  );
}
